name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: |
        dotnet restore
    
    - name: Publish [WIN-x64]
      run: |
        dotnet publish --configuration Release --runtime win-x64 --framework net6.0 --self-contained true -p:ReadyToRun=true
        
    - name: Install zip
      uses: montudor/action-zip@v1
        
    - name: Zip [WIN-X64]
      run: |
        cd Discreet/bin/Release/net6.0/win-x64
        zip -qq -r win-x64.zip publish
        
    - name: Publish [LINUX-x64]
      run: |
        dotnet publish --configuration Release --runtime linux-x64 --framework net6.0 --self-contained true
        
    - name: Tar bz2 [LINUX-x64]
      run: |
        cd Discreet/bin/Release/net6.0/linux-x64
        tar cfvj linux-x64.tar.bz2 publish
        
    - uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 0
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Create the Github Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: assets
        body: CHANGELOG
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Upload [WIN-x64] archive to the release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Discreet/bin/Release/net6.0/win-x64/win-x64.zip
        asset_name: win-x64.zip
        asset_content_type: application/zip

    - name: upload linux tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Discreet/bin/Release/net6.0/linux-x64/linux-x64.tar.bz2
        asset_name: linux-x64.tar.bz2
        asset_content_type: application/bzip2
